### ISSUE TITLE
Error when starting from scratch

### ISSUE THREAD

**Issue by otavio** [GerritCodeReview/k8s-gerrit#13]
I'm trying to start a site from scratch and it is erroring out as:

```console
[2022-01-22 01:37:08,211] DEBUG SHA1 of file '/var/plugins/healthcheck.jar' is e968e7e833fcf39aa5de1e3511fbff9f06ae35cc
[2022-01-22 01:37:08,212] DEBUG SHA1 of file '/var/gerrit/plugins/healthcheck.jar' is e968e7e833fcf39aa5de1e3511fbff9f06ae35cc
[2022-01-22 01:37:08,212] INFO Installing packaged plugin reviewnotes.
[2022-01-22 01:37:08,270] INFO Installing packaged plugin replication.
[2022-01-22 01:37:08,278] INFO Installing packaged plugin commit-message-length-validator.
[2022-01-22 01:37:08,284] INFO Installing packaged plugin download-commands.
[2022-01-22 01:37:08,297] DEBUG SHA1 of file '/var/gerrit/plugins/gerrit-oauth-provider.jar' is 01b221a18cc2ebc1906def6470563c15145b64f9
[2022-01-22 01:37:16,084] INFO Installed Gerrit version: gerrit version 3.5.0.1; Provided Gerrit version: gerrit version 3.5.0.1).
[2022-01-22 01:37:16,085] INFO No initialization required.
[2022-01-22 01:37:16,613] INFO Index accounts not ready.
[2022-01-22 01:37:16,613] INFO Index groups not ready.
[2022-01-22 01:37:16,613] INFO Starting to reindex.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gerrit.common.IoUtil (file:/home/gerrit/.gerritcodereview/tmp/gerrit_227876187591655698_app/com_google_gerrit_common_libserver.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of com.google.gerrit.common.IoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2022-01-22 01:37:23,190] [main] INFO  com.google.gerrit.server.git.SystemReaderInstaller : Set JGit's SystemReader to read system config from /var/gerrit/etc/jgit.config
[2022-01-22 01:37:23,284] [main] INFO  com.google.gerrit.server.git.LocalDiskRepositoryManager : Defaulting core.streamFileThreshold to 248m
[2022-01-22 01:37:27,985] [main] INFO  com.google.gerrit.server.cache.PersistentCacheBaseFactory : Enabling disk cache /var/gerrit/cache
[2022-01-22 01:37:28,287] [main] INFO  com.google.gerrit.server.git.WorkQueue : Adding metrics for 'WorkQueue' queue
[2022-01-22 01:37:28,381] [main] INFO  com.google.gerrit.server.git.WorkQueue : Adding metrics for 'Index-Interactive' queue
[2022-01-22 01:37:28,386] [main] INFO  com.google.gerrit.server.git.WorkQueue : Adding metrics for 'Index-Batch' queue
[2022-01-22 01:37:28,987] [main] INFO  com.google.gerrit.server.git.WorkQueue : Adding metrics for 'ReceiveCommits' queue
[2022-01-22 01:37:28,987] [main] INFO  com.google.gerrit.server.git.WorkQueue : Adding metrics for 'SendEmail' queue
[2022-01-22 01:37:29,187] [main] INFO  com.google.gerrit.server.rules.PrologEnvironment : reductionLimit: 100000, compileLimit: 1000000
[2022-01-22 01:37:31,191] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loading plugins from /var/gerrit/plugins
[2022-01-22 01:37:34,778] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin commit-message-length-validator, version v3.5.0.1
[2022-01-22 01:37:34,883] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin download-commands, version v3.5.0.1
[2022-01-22 01:37:34,987] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin gerrit-oauth-provider, version ab09506
[2022-01-22 01:37:35,092] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin healthcheck, version v3.3.0-27-g661b1d0055
[2022-01-22 01:37:35,184] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin replication, version v3.5.0.1
[2022-01-22 01:37:35,278] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin reviewnotes, version v3.5.0.1
[2022-01-22 01:37:35,585] [main] ERROR com.google.gerrit.server.index.account.AllAccountsIndexer : Error collecting accounts
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: Cannot open repository All-Users
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:168)
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:156)
        at com.google.gerrit.server.account.Accounts.readUserRefs(Accounts.java:145)
        at com.google.gerrit.server.account.Accounts.allIds(Accounts.java:116)
        at com.google.gerrit.server.index.account.AllAccountsIndexer.collectAccounts(AllAccountsIndexer.java:133)
        at com.google.gerrit.server.index.account.AllAccountsIndexer.indexAll(AllAccountsIndexer.java:75)
        at com.google.gerrit.server.index.account.AllAccountsIndexer.indexAll(AllAccountsIndexer.java:47)
        at com.google.gerrit.pgm.Reindex.reindex(Reindex.java:241)
        at com.google.gerrit.pgm.Reindex.reindex(Reindex.java:139)
        at com.google.gerrit.pgm.Reindex.run(Reindex.java:118)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:224)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:120)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:65)
        at Main.main(Main.java:28)
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /var/mnt/git/All-Users
        at org.eclipse.jgit.lib.RepositoryCache$FileKey.open(RepositoryCache.java:412)
        at org.eclipse.jgit.lib.RepositoryCache.openRepository(RepositoryCache.java:245)
        at org.eclipse.jgit.lib.RepositoryCache.open(RepositoryCache.java:88)
        at org.eclipse.jgit.lib.RepositoryCache.open(RepositoryCache.java:61)
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:166)
        ... 18 more
[2022-01-22 01:37:38,882] [main] ERROR com.google.gerrit.server.index.group.AllGroupsIndexer : Error collecting groups
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: Cannot open repository All-Users
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:168)
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:156)
        at com.google.gerrit.server.group.db.Groups.getAllGroupReferences(Groups.java:139)
        at com.google.gerrit.server.index.group.AllGroupsIndexer.collectGroups(AllGroupsIndexer.java:145)
        at com.google.gerrit.server.index.group.AllGroupsIndexer.indexAll(AllGroupsIndexer.java:79)
        at com.google.gerrit.server.index.group.AllGroupsIndexer.indexAll(AllGroupsIndexer.java:51)
        at com.google.gerrit.pgm.Reindex.reindex(Reindex.java:241)
        at com.google.gerrit.pgm.Reindex.reindex(Reindex.java:139)
        at com.google.gerrit.pgm.Reindex.run(Reindex.java:118)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:224)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:120)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:65)
        at Main.main(Main.java:28)
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /var/mnt/git/All-Users
        at org.eclipse.jgit.lib.RepositoryCache$FileKey.open(RepositoryCache.java:412)
        at org.eclipse.jgit.lib.RepositoryCache.openRepository(RepositoryCache.java:245)
        at org.eclipse.jgit.lib.RepositoryCache.open(RepositoryCache.java:88)
        at org.eclipse.jgit.lib.RepositoryCache.open(RepositoryCache.java:61)
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:166)
        ... 17 more
[2022-01-22 01:37:39,989] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin replication, version v3.5.0.1
[2022-01-22 01:37:39,990] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin commit-message-length-validator, version v3.5.0.1
[2022-01-22 01:37:39,991] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin healthcheck, version v3.3.0-27-g661b1d0055
[2022-01-22 01:37:39,992] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin gerrit-oauth-provider, version ab09506
[2022-01-22 01:37:39,993] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin reviewnotes, version v3.5.0.1
[2022-01-22 01:37:39,993] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin download-commands, version v3.5.0.1
[2022-01-22 01:37:40,172] [main] INFO  com.google.gerrit.server.plugins.CleanupHandle : Cleaned plugin plugin_replication_220122_0137_7720452457405515936.jar
[2022-01-22 01:37:40,172] [main] INFO  com.google.gerrit.server.plugins.CleanupHandle : Cleaned plugin plugin_commit-message-length-validator_220122_0137_1350513704137723960.jar
[2022-01-22 01:37:40,173] [main] INFO  com.google.gerrit.server.plugins.CleanupHandle : Cleaned plugin plugin_healthcheck_220122_0137_16950269517788202622.jar
[2022-01-22 01:37:40,174] [main] INFO  com.google.gerrit.server.plugins.CleanupHandle : Cleaned plugin plugin_gerrit-oauth-provider_220122_0137_7509528736793333491.jar
[2022-01-22 01:37:40,175] [main] INFO  com.google.gerrit.server.plugins.CleanupHandle : Cleaned plugin plugin_reviewnotes_220122_0137_1744644286068154864.jar
[2022-01-22 01:37:40,176] [main] INFO  com.google.gerrit.server.plugins.CleanupHandle : Cleaned plugin plugin_download-commands_220122_0137_14404405900742881639.jar
[2022-01-22 01:37:40,370] ERROR An error occured, when reindexing Gerrit indices. Exit code: 1
```

**Comment by thomasdraebing** [comment]
Hi @otavio,

apparently the script deciding whether an initialization is required, though that is not the case: `[2022-01-22 01:37:16,085] INFO No initialization required.`. However, for some reason the `All-Users`-repository is not present in the site. I guess, that is because you exchanged or cleaned the volume containing the repositories, but are reusing the volume containing the rest of the site, which is created by the StatefulSet (and will survive an uninstallation of the chart). The easiest way to resolve this would be to delete the volume containing the site. This will delete the indices and caches, but since you seem to install a fresh site anyway that shouldn't be an issue.

Nevertheless, a new check should be added for such a case. Just doing an init in such a situation might not be a good idea, since the existing site does not reflect the state of the repositories, but at least a better error message should be printed.

*Please note*: The repository on GitHub is only a mirror. The main repository can be found here: https://gerrit-review.googlesource.com/admin/repos/k8s-gerrit,general. In the future please ask questions on the Gerrit mailing list: https://groups.google.com/g/repo-discuss?hl=en.
