### ISSUE TITLE
gerrit-replica-git-repositories-init fail

### ISSUE THREAD

**Issue by hillbun** [GerritCodeReview/k8s-gerrit#15]
error is below， how to fix?  thanks.

```
java.io.IOException: Mount point not found
        at java.base/sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:105)
        at java.base/sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:67)
        at java.base/sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:49)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:369)
        at java.base/java.nio.file.Files.getFileStore(Files.java:1487)
        at org.eclipse.jgit.util.FS$FileStoreAttributes.getFileStoreAttributes(FS.java:362)
        at org.eclipse.jgit.util.FS$FileStoreAttributes.get(FS.java:346)
        at org.eclipse.jgit.util.FS.getFileStoreAttributes(FS.java:913)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:226)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:207)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:104)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.scanRef(RefDirectory.java:1094)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.readRef(RefDirectory.java:1064)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.readAndResolve(RefDirectory.java:264)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.firstExactRef(RefDirectory.java:318)
        at org.eclipse.jgit.lib.RefDatabase.findRef(RefDatabase.java:271)
        at org.eclipse.jgit.internal.storage.file.RefDirectoryUpdate.tryLock(RefDirectoryUpdate.java:57)
        at org.eclipse.jgit.lib.RefUpdate.link(RefUpdate.java:678)
        at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:246)
        at com.google.gerrit.server.git.LocalDiskRepositoryManager.createRepository(LocalDiskRepositoryManager.java:200)
        at com.google.gerrit.server.schema.AllUsersCreator.create(AllUsersCreator.java:96)
        at com.google.gerrit.server.schema.SchemaCreatorImpl.create(SchemaCreatorImpl.java:104)
        at com.google.gerrit.server.schema.SchemaCreatorImpl.ensureCreated(SchemaCreatorImpl.java:127)
        at com.google.gerrit.server.schema.NoteDbSchemaUpdater.ensureSchemaCreated(NoteDbSchemaUpdater.java:105)
        at com.google.gerrit.server.schema.NoteDbSchemaUpdater.update(NoteDbSchemaUpdater.java:81)
        at com.google.gerrit.pgm.init.BaseInit$SiteRun.upgradeSchema(BaseInit.java:360)
        at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:123)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:224)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:120)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:65)
        at Main.main(Main.java:28)
ERROR org.eclipse.jgit.util.FS : Mount point not found
java.io.IOException: Mount point not found
        at java.base/sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:105)
        at java.base/sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:67)
        at java.base/sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:49)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:369)
        at java.base/java.nio.file.Files.getFileStore(Files.java:1487)
        at org.eclipse.jgit.util.FS$FileStoreAttributes.getFileStoreAttributes(FS.java:362)
        at org.eclipse.jgit.util.FS$FileStoreAttributes.get(FS.java:346)
        at org.eclipse.jgit.util.FS.getFileStoreAttributes(FS.java:913)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:226)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:207)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:104)
        at org.eclipse.jgit.internal.storage.file.PackDirectory.scanPacksImpl(PackDirectory.java:418)
        at org.eclipse.jgit.internal.storage.file.PackDirectory.scanPacks(PackDirectory.java:407)
        at org.eclipse.jgit.internal.storage.file.PackDirectory.searchPacksAgain(PackDirectory.java:341)
        at org.eclipse.jgit.internal.storage.file.PackDirectory.getPack(PackDirectory.java:163)
        at org.eclipse.jgit.internal.storage.file.PackDirectory.has(PackDirectory.java:130)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.hasPackedObject(ObjectDirectory.java:298)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.hasPackedInSelfOrAlternate(ObjectDirectory.java:267)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.hasPackedOrLooseInSelfOrAlternate(ObjectDirectory.java:261)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.has(ObjectDirectory.java:255)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:76)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:56)
        at org.eclipse.jgit.lib.ObjectInserter.insert(ObjectInserter.java:333)
        at com.google.gerrit.server.git.meta.VersionedMetaData.saveFile(VersionedMetaData.java:629)
        at com.google.gerrit.server.git.meta.VersionedMetaData.saveUTF8(VersionedMetaData.java:615)
        at com.google.gerrit.server.git.meta.VersionedMetaData.saveConfig(VersionedMetaData.java:611)
        at com.google.gerrit.server.project.ProjectConfig.onSave(ProjectConfig.java:1276)
        at com.google.gerrit.server.git.meta.VersionedMetaData$1.doSave(VersionedMetaData.java:334)
        at com.google.gerrit.server.git.meta.VersionedMetaData$1.write(VersionedMetaData.java:350)
        at com.google.gerrit.server.git.meta.VersionedMetaData$1.write(VersionedMetaData.java:321)
        at com.google.gerrit.server.git.meta.VersionedMetaData.commit(VersionedMetaData.java:207)
        at com.google.gerrit.server.schema.AllUsersCreator.initAllUsers(AllUsersCreator.java:150)
        at com.google.gerrit.server.schema.AllUsersCreator.create(AllUsersCreator.java:97)
        at com.google.gerrit.server.schema.SchemaCreatorImpl.create(SchemaCreatorImpl.java:104)
        at com.google.gerrit.server.schema.SchemaCreatorImpl.ensureCreated(SchemaCreatorImpl.java:127)
        at com.google.gerrit.server.schema.NoteDbSchemaUpdater.ensureSchemaCreated(NoteDbSchemaUpdater.java:105)
        at com.google.gerrit.server.schema.NoteDbSchemaUpdater.update(NoteDbSchemaUpdater.java:81)
        at com.google.gerrit.pgm.init.BaseInit$SiteRun.upgradeSchema(BaseInit.java:360)
        at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:123)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:224)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:120)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:65)
        at Main.main(Main.java:28)
Initialized /var/gerrit

```

**Comment by hillbun** [comment]
@thomasdraebing 

I install gerrit by helm chart, is it possible to fix this temporarily?

and when will new version of helm chart will be released?

**Comment by thomasdraebing** [comment]
I will ping some reviewers today and rebuild the container images. An update of the helm chart is not required. You would just have to update the version of the container images.

**Comment by thomasdraebing** [comment]
The images are published.
